name: CI Setup

on:
  push:
    branches: [ main, setup-task ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check Python Version
        run: python --version
